WeightTracker/Models/Person.cs
using System.ComponentModel.DataAnnotations;

namespace WeightTracker.Models
{
    public class Person
    {
        [Key] public int Id { get; set; }

        [Display(Name = "Vorname")]
        [Required(ErrorMessage = "Vorname ist erforderlich!")]
        [StringLength(50, ErrorMessage = "Max. ist 50 Zeichen.")]
        public string FirstName { get; set; }

        [Display(Name = "Nachname")]
        [Required(ErrorMessage = "Nachname ist erforderlich!")]
        [StringLength(50, ErrorMessage = "Max. ist 50 Zeichen.")]
        public string LastName { get; set; }

        [Display(Name = "Alter")]
        [Required(ErrorMessage = "Alter ist erforderlich!")]
        [Range(1, 125, ErrorMessage = "Alter zwischen 1 und 125 Jahren")]
        public int Age { get; set; }

        public virtual string Name => $"{FirstName} {LastName}";
    }
}

WeightTracker/Models/StatisticsViewModel.cs
using System.Collections.Generic;

namespace WeightTracker.Models
{
    public class StatisticsViewModel
    {
        public List<List<object>> StatisticList { get; set; }
    }
}

WeightTracker/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using WeightTracker.Data;
using WeightTracker.Models;

namespace WeightTracker.Controllers
{
    public class HomeController : Controller
    {
        private readonly ApplicationDbContext _context;

        public HomeController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var persons = _context.Person.ToList();
            var weightTracking = _context.WeightTracking.ToList();

            var personTracking = new Dictionary<Person, List<WeightTracking>>();
            persons.ForEach(person =>
            {
                var personWeightTracking = weightTracking.FindAll(tracking => tracking.PersonId == person.Id)
                    .OrderByDescending(tracking => tracking.Date).ToList();
                personTracking.Add(person, personWeightTracking);
            });

            return View(new WeightTrackingViewModel
            {
                PersonTracking = personTracking
            });
        }

        public IActionResult Persons()
        {
            return View(_context.Person.ToList());
        }

        public IActionResult Statistics()
        {
            const int numberOfDays = 7;

            var persons = _context.Person.ToList().OrderBy(person => person.Id).ToList();
            if (persons.Count == 0)
                return View(new StatisticsViewModel());

            var weightTracking = _context.WeightTracking.ToList()
                .FindAll(tracking => tracking.Date >= DateTime.Now.AddDays(-numberOfDays))
                .OrderByDescending(tracking => tracking.Date);

            var statisticListHeader = new List<object> {"Datum"}
                .Concat(persons.Select(person => person.Name).ToList())
                .ToList();
            var statisticList = new List<List<object>> {statisticListHeader};

            var date = DateTime.Now;
            while (date > DateTime.Now.AddDays(-7))
            {
                var weightTrackings = persons.Select(person =>
                        weightTracking.FirstOrDefault(tracking =>
                            tracking.PersonId == person.Id && tracking.Date.Date == date.Date))
                    .Select(tracking => tracking == null ? (object) null : tracking.Weight)
                    .ToList();

                var enumerable =
                    new List<object> {date.Date.ToString("dd.MM.yyyy")}
                        .Concat(weightTrackings)
                        .ToList();

                statisticList.Add(enumerable);
                date = date.AddDays(-1);
            }

            return View(new StatisticsViewModel {StatisticList = statisticList});
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
        }
    }
}

WeightTracker/Controllers/PersonController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WeightTracker.Data;
using WeightTracker.Models;

namespace WeightTracker.Controllers
{
    public class PersonController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PersonController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Create()
        {
            return View(new Person());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Person person)
        {
            if (!ModelState.IsValid) return View(person);

            _context.Add(person);
            await _context.SaveChangesAsync();
            return RedirectToAction("Persons", "Home");
        }

        public IActionResult Edit(int? id)
        {
            if (id == null) return NotFound();

            var person = _context.Person.SingleOrDefault(x => x.Id == id);
            if (person == null) return NotFound();

            return View(person);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Person person)
        {
            if (id != person.Id) return NotFound();

            if (!ModelState.IsValid) return View(person);

            try
            {
                _context.Update(person);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!PersonExists(person.Id))
                    return NotFound();

                throw;
            }

            return RedirectToAction("Persons", "Home");
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return NotFound();

            var person = await _context.Person.SingleOrDefaultAsync(x => x.Id == id);
            if (person == null) return NotFound();

            return View(person);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var person = await _context.Person.FindAsync(id);
            _context.Person.Remove(person);
            await _context.SaveChangesAsync();
            return RedirectToAction("Persons", "Home");
        }

        private bool PersonExists(int id)
        {
            return _context.Person.Any(e => e.Id == id);
        }
    }
}

WeightTracker/Controllers/WeightTrackingController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WeightTracker.Data;
using WeightTracker.Models;

namespace WeightTracker.Controllers
{
    public class WeightTrackingController : Controller
    {
        private readonly ApplicationDbContext _context;

        public WeightTrackingController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Create(int? id)
        {
            if (id == null) return NotFound();

            var person = _context.Person.FirstOrDefault(x => x.Id == id);
            if (person == null) return NotFound();

            return View(new WeightTracking
            {
                Date = DateTime.Today,
                PersonId = person.Id,
                Person = person
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int id, WeightTracking tracking)
        {
            tracking.Person = _context.Person.FirstOrDefault(x => x.Id == id);
            if (tracking.Person == null) return NotFound();

            tracking.Id = 0;
            tracking.PersonId = tracking.Person.Id;

            if (!ModelState.IsValid) return View(tracking);

            var sameDateTracking =
                _context.WeightTracking.FirstOrDefault(x => (x.PersonId == id && x.Date == tracking.Date));
            if (sameDateTracking != null)
            {
                ModelState.AddModelError("Date", "Datum wurde schon verwendet.");
                return View(tracking);
            }

            _context.Add(tracking);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", "Home");
        }

        public IActionResult Edit(int? id)
        {
            if (id == null) return NotFound();

            var tracking = _context.WeightTracking.SingleOrDefault(x => x.Id == id);
            if (tracking == null) return NotFound();

            tracking.Person = _context.Person.SingleOrDefault(person => person.Id == tracking.PersonId);

            return View(tracking);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, WeightTracking tracking)
        {
            if (id != tracking.Id) return NotFound();

            if (!ModelState.IsValid) return View(tracking);

            try
            {
                _context.Entry(tracking).State = EntityState.Detached;
                var tempTracking = _context.WeightTracking.FirstOrDefault(x => x.Id == id);
                if (tempTracking == null)
                    return RedirectToAction("Index", "Home");

                var sameDateTracking =
                    _context.WeightTracking.FirstOrDefault(x =>
                        (x.PersonId == tempTracking.PersonId && x.Date == tracking.Date));
                if (sameDateTracking != null && sameDateTracking.Id != id)
                {
                    ModelState.AddModelError("Date", "Datum wurde schon verwendet.");
                    return View(tracking);
                }

                tracking.PersonId = tempTracking.PersonId;
                tracking.Person = tempTracking.Person;

                _context.Entry(tempTracking).CurrentValues.SetValues(tracking);
                _context.Update(tempTracking);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!WeightTrackingExists(tracking.Id))
                    return NotFound();

                throw;
            }

            return RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return NotFound();

            var tracking = await _context.WeightTracking.SingleOrDefaultAsync(x => x.Id == id);
            if (tracking == null) return NotFound();

            return View(tracking);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tracking = await _context.WeightTracking.FindAsync(id);
            _context.WeightTracking.Remove(tracking);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", "Home");
        }

        private bool WeightTrackingExists(int id)
        {
            return _context.WeightTracking.Any(e => e.Id == id);
        }
    }
}

WeightTracker/Views/Home/Index.cshtml
@model WeightTrackingViewModel
@{
    ViewData["Title"] = "Home Page";
}

<div>
    <div class="header">
        <h1>Übersicht</h1>
    </div>
    <hr/>
    <div class="row">
        @if (Model.PersonTracking.Count == 0)
        {
            <div class="col-md-12">
                <h5>Keine Person gefunden. Bitte erst eine Person erstellen</h5>
            </div>
        }
        @foreach (var personTrackings in Model.PersonTracking)
        {
            <div class="col-md-12">
                <h2>
                    @Html.DisplayFor(tracking => personTrackings.Key.Name)

                    <a asp-action="Create" asp-controller="WeightTracking" asp-route-id="@personTrackings.Key.Id">
                        <img id="icon-small" src="~/images/Document/AddNews.png" title="Erstellen" alt="Erstellen"/>
                    </a>
                </h2>

                <table class="table">
                    <thead>
                    <tr>
                        <th style="width: 25%">Datum</th>
                        <th style="width: 40%">Gewicht</th>
                        <th>Aktionen</th>
                    </tr>
                    </thead>
                    <tbody>
                    @if (personTrackings.Value.Count == 0)
                    {
                        <tr>
                            <td>
                                Keine Daten gefunden
                            </td>
                        </tr>
                    }
                    @foreach (var tracking in personTrackings.Value)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => tracking.Date)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => tracking.Weight) KG
                            </td>
                            <td>
                                <a asp-controller="WeightTracking" asp-action="Edit" asp-route-id="@tracking.Id">
                                    <img id="icon-small" src="~/images/Document/EditNews.png" title="Bearbeiten" alt="Bearbeiten"/>
                                </a> |
                                <a asp-controller="WeightTracking" asp-action="Delete" asp-route-id="@tracking.Id">
                                    <img id="icon-small" src="~/images/Document/DeleteNews.png" title="Löschen" alt="Löschen"/>
                                </a>
                            </td>
                        </tr>
                    }
                    </tbody>
                </table>
            </div>
        }
    </div>
</div>

WeightTracker/Views/Home/Persons.cshtml
@model IEnumerable<Person>
@{
    ViewData["Title"] = "Personen";
}

<div>
    <div class="header">
        <h1>Personen</h1>
    </div>
    <hr/>
    <div class="row">
        <div class="col-md-12">
            <div>
                <a asp-action="Create" asp-controller="Person">
                    <img id="icon-small" src="~/images/Document/AddNews.png" title="Erstellen" alt="Erstellen"/>
                </a>
            </div>
            <table class="table">
                <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.FirstName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.LastName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Age)
                    </th>
                    <th>
                        Aktionen
                    </th>
                </tr>
                </thead>
                <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.FirstName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.LastName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Age)
                        </td>
                        <td>
                            <a asp-controller="Person" asp-action="Edit" asp-route-id="@item.Id">
                                <img id="icon-small" src="~/images/Document/EditNews.png" title="Bearbeiten" alt="Bearbeiten"/>
                            </a> |
                            <a asp-controller="Person" asp-action="Delete" asp-route-id="@item.Id">
                                <img id="icon-small" src="~/images/Document/DeleteNews.png" title="Löschen" alt="Löschen"/>
                            </a>
                        </td>
                    </tr>
                }
                </tbody>
            </table>
        </div>
    </div>
</div>

WeightTracker/Views/Home/Statistics.cshtml
@model StatisticsViewModel
@{
    ViewData["Title"] = "Statistics";
}
<script src="~/myLib/js/gLoader.js"></script>
<script type="text/javascript">
    google.charts.load("current", {packages:["corechart"]});
    google.charts.setOnLoadCallback(drawChart);
    
    function drawChart() { 
        const data2 = google.visualization.arrayToDataTable(@Html.Raw(Json.Serialize(Model.StatisticList)));
        
        const options = {
          curveType: 'function',
          legend: { position: 'bottom' }
        };

        const chart = new google.visualization.LineChart(document.getElementById('curve_chart'));

        chart.draw(data2, options);
      }
</script>

<div>
    <div class="header">
        <h1>Statistik</h1>
    </div>
    <hr/>
    <div class="row">
        @if (Model.StatisticList != null)
        {
            <div class="col-md-12">
                <h1>Gewicht der letzten 7 Tage</h1>
            </div>
            <div class="col-md-12">
                <div id="curve_chart" style="height: 500px;"></div>
            </div>
        }
        else
        {
            <div class="col-md-12">
                <h1>Keine Daten gefunden</h1>
            </div>
        }
    </div>
</div>